site_name: shoper 
site_url: !ENV [SITE_URL, "https://docs.scandidreams.top/"]  # 假设：你有自定义域名
repo_url: https://github.com/scandishoper/shoper-docs
repo_name: scandishoper/shoper-docs

theme:
  name: material
  custom_dir: overrides
  logo: assets/2026-2-16-3.png
  favicon: assets/2026-2-16-2.png
  language: zh
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer     # 底部上一页/下一页（长文/系列很舒服）
    - navigation.expand     # 自动展开当前分支
    - navigation.path       # 显示当前页面路径（定位感强）
    - navigation.prune      # 折叠无关分支，目录不爆炸
    - header.autohide
    - toc.follow


plugins:
  - search:
      lang: zh
  - tags
  - blog
  - git-revision-date-localized:
      enabled: !ENV [CI, false]        # 本地默认关闭，CI 打开
      enable_creation_date: true
  - git-authors:
      enabled: !ENV [CI, false]        # 本地默认关闭，CI 打开
      show_email_address: false
      fallback_to_empty: true
  - encryptcontent:
      enabled: !ENV [ENABLE_PRIVATE, false]  # 可选：只在需要时启用
      title_prefix: "[受保护] "
      global_password: ""
      remember_password: true
  - rss:
      enabled: !ENV [CI, false]
  - redirects:
      enabled: !ENV [CI, false]
  - minify:
      enabled: !ENV [CI, false]
  - projects

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/consent.js

extra:
  consent:
    title: Cookie consent
    description: >- 
      我使用 cookies 来识别您的重复访问和偏好，以及其他信息
      以评估我的文档的有效性以及用户是否
      找到他们正在寻找的东西。在你同意的情况下，你正在帮助我实现目标。
      让我的文档更好。
    cookies:
      analytics: Custom name
    actions:
      - accept
      - manage 
  analytics:
    provider: google
    property: G-8JQ8PJF435 
    feedback:
      title: 这个页面对你有帮助吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 有帮助
          data: 1
          note: >-
            感谢你的反馈！
        - icon: material/emoticon-sad-outline
          name: 需要改进
          data: 0
          note: >-
            感谢你的反馈！欢迎通过
            <a href="..." target="_blank" rel="noopener">反馈表单</a>
            告诉我哪里可以做得更好。
  generator: false
  repo:
    facts:
      - version
      - stars
      - forks
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scandishoper

copyright: >
  Copyright &copy; 2026 shoper –
  <a href="#__consent">Change cookie settings</a>

  

nav:
  - 主页: index.md

  - 算法:
      - index: algo/index.md
      - 基础:
          - 二分: algo/p2.md
          - 三分: algo/p1.md
          - 位运算: algo/p5.md
          - 高精度算法: algo/p16.md
          - 曼哈顿距离与切比雪夫距离的转换: algo/p11.md
      - 常见算法:
          - 排序算法: algo/p9.md
          - 贪心-局部交叉型: algo/p14.md
          - 背包九讲: algo/p13.md
          - 六六表-数构造: algo/p6.md
      - 数据结构:
          - 栈-队列-双端: algo/p12.md
          - 优先-map-set: algo/p4.md
          - 并查集: algo/p8.md
          - 二叉树的遍历: algo/p3.md
      - 数论:
          - 数论: algo/p10.md
          - 逆元-取余公式-快速幂算法: algo/p15.md
      - 图论:
          - 图论: algo/p7.md

  - 题解:
      - index: solutions/index.md
      - Codeforces Hello 2026: solutions/p35.md
      - Codeforces Round 1071 (Div. 3) 题解: solutions/p36.md
      - Codeforces Round 1072 (Div. 3)题解: solutions/p37.md
      - Codeforces Round 1075 (Div. 2) 题解: solutions/p38.md
      - Codeforces Round 1076 (Div. 3) 题解: solutions/p39.md
      - Codeforces Round 1077 (Div. 2)题解: solutions/p40.md
      - Codeforces Round 1078 (Div. 2) 题解: solutions/p41.md
      - wustoj-cpp: solutions/p42.md

  - csdiy:
      - index: csdiy/index.md
      - CSAPP-note: csdiy/p34.md

  - 技术:
      - index: technology/index.md
      - AI翻译插件配置教程: technology/p43.md
      - hexo博客搭建: technology/p44.md
      - 在学校内上传博文报错的解决: technology/p45.md
      - 智慧树军事课脚本: technology/p46.md
      - 自动刷题刷课: technology/p47.md

  - 看法:
      - index: views/index.md
      - EP56《亲密关系》：在一起的意义是照见自己: views/p48.md
      - 高中思维转变: views/p53.md
      - 如何看待试点班: views/p51.md
      - 计算机专业如何入门（ACMer 版: views/p52.md
      - 在武科大中如何真正学习: views/p50.md
      - 《囧妈》观后感: views/p49.md

  - 博客:
      - index: blog/index.md
      - 学期与杂谈:
          - 大一上: blog/p28.md
          - 大一寒假: blog/p30.md
          - 大一寒假题单: blog/p31.md
          - 我的大一下: blog/p33.md
          - 大一下暑假杂谈: blog/p29.md
          - 大二上随笔: blog/p32.md
      - 周记:
          - 周记1: blog/p18.md
          - 周记2: blog/p21.md
          - 周记3: blog/p22.md
          - 周记4: blog/p23.md
          - 周记6: blog/p24.md
          - 周记7: blog/p25.md
          - 周记8: blog/p26.md
          - 周记9: blog/p27.md
          - 周记11: blog/p19.md
          - 周记13: blog/p20.md
  
  - 友链:
      - index: link/index.md
